development:
  url: {{envOr "MYSQLCONNSTR_DATABASE_URL" "mysql://root:root@(localhost:3306)/musicvotes_production?parseTime=true&multiStatements=true&readTimeout=1s"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/musicvotes_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "MYSQLCONNSTR_DATABASE_URL" "mysql://root:root@(localhost:3306)/musicvotes_production?parseTime=true&multiStatements=true&readTimeout=1s"}}