package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/marstr/musicvotes/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Song)
// DB Table: Plural (songs)
// Resource: Plural (Songs)
// Path: Plural (/songs)
// View Template Folder: Plural (/templates/songs/)

// SongsResource is the resource for the Song model
type SongsResource struct {
	buffalo.Resource
}

// List gets all Songs. This function is mapped to the path
// GET /songs
func (v SongsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	songs := &models.Songs{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Songs from the DB
	if err := q.All(songs); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, songs))
}

// Show gets the data for one Song. This function is mapped to
// the path GET /songs/{song_id}
func (v SongsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Song
	song := &models.Song{}

	// To find the Song the parameter song_id is used.
	if err := tx.Find(song, c.Param("song_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, song))
}

// New renders the form for creating a new Song.
// This function is mapped to the path GET /songs/new
func (v SongsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Song{}))
}

// Create adds a Song to the DB. This function is mapped to the
// path POST /songs
func (v SongsResource) Create(c buffalo.Context) error {
	// Allocate an empty Song
	song := &models.Song{}

	// Bind song to the html form elements
	if err := c.Bind(song); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(song)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, song))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Song was created successfully")

	// and redirect to the songs index page
	return c.Render(201, r.Auto(c, song))
}

// Edit renders a edit form for a Song. This function is
// mapped to the path GET /songs/{song_id}/edit
func (v SongsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Song
	song := &models.Song{}

	if err := tx.Find(song, c.Param("song_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, song))
}

// Update changes a Song in the DB. This function is mapped to
// the path PUT /songs/{song_id}
func (v SongsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Song
	song := &models.Song{}

	if err := tx.Find(song, c.Param("song_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Song to the html form elements
	if err := c.Bind(song); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(song)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, song))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Song was updated successfully")

	// and redirect to the songs index page
	return c.Render(200, r.Auto(c, song))
}

// Destroy deletes a Song from the DB. This function is mapped
// to the path DELETE /songs/{song_id}
func (v SongsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Song
	song := &models.Song{}

	// To find the Song the parameter song_id is used.
	if err := tx.Find(song, c.Param("song_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(song); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Song was destroyed successfully")

	// Redirect to the songs index page
	return c.Render(200, r.Auto(c, song))
}
